'use client';

import { useState } from 'react';
import FAQSection from '@/components/UI/FAQSection';
import ToolHeader from '@/components/UI/ToolHeader';
import { calculators } from '@/utils/calculators';

const PREFIXES = ['Elite', 'Global', 'Apex', 'Prime', 'Nex', 'Nova', 'Swift', 'Bright'];
const SUFFIXES = ['Solutions', 'Hub', 'Labs', 'Flow', 'Craft', 'Bridge', 'Pulse', 'Edge'];

export default function BusinessNameGenerator() {
    const [keyword, setKeyword] = useState('');
    const [names, setNames] = useState<string[]>([]);

    const generateNames = () => {
        const kw = keyword.trim() || 'Project';
        const result = new Set<string>();

        while (result.size < 12) {
            const type = Math.floor(Math.random() * 3);
            if (type === 0) result.add(`${PREFIXES[Math.floor(Math.random() * PREFIXES.length)]}${kw}`);
            else if (type === 1) result.add(`${kw}${SUFFIXES[Math.floor(Math.random() * SUFFIXES.length)]}`);
            else result.add(`${PREFIXES[Math.floor(Math.random() * PREFIXES.length)]} ${kw} ${SUFFIXES[Math.floor(Math.random() * SUFFIXES.length)]}`);
        }
        setNames(Array.from(result));
    };

    const faqs = [
        {
            question: "How do I choose the right business name?",
            answer: "A good name should be easy to pronounce, memorable, and reflect your brand's values. Check if the domain and social handles are available before committing."
        },
        {
            question: "Are these names unique?",
            answer: "These names are generated by combining professional prefixes and suffixes. While they sound elite, you should always perform a trademark search to ensure they aren't already in use."
        },
        {
            question: "Why include my keyword?",
            answer: "Including a keyword related to your industry (e.g., 'Cloud' for tech, 'Green' for eco-friendly) helps customers immediately understand what you do."
        }
    ];

    const calc = calculators.find(c => c.href === '/business-name');

    return (
        <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <ToolHeader
                title={calc?.title || 'Business Name Generator'}
                description={calc?.description || 'Launch your next big idea with a professional brand name.'}
            />

            <div className="card" style={{ marginBottom: '3rem' }}>
                <div style={{ display: 'grid', gap: '2rem' }}>
                    <div style={{ display: 'flex', gap: '1rem' }}>
                        <input
                            type="text"
                            className="input"
                            value={keyword}
                            onChange={(e) => setKeyword(e.target.value)}
                            placeholder="e.g. Tech, Eco, Fitness"
                            style={{ flex: 1 }}
                        />
                        <button onClick={generateNames} className="btn btn-primary" style={{ padding: '0.75rem 1.5rem' }}>Generate Names</button>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '1rem' }}>
                        {names.map((name, i) => (
                            <div key={i} style={{
                                background: 'rgba(30, 41, 59, 0.4)',
                                padding: '1.25rem',
                                borderRadius: '1rem',
                                border: '1px solid rgba(255, 255, 255, 0.05)',
                                textAlign: 'center',
                                fontWeight: 700,
                                color: '#fff',
                                cursor: 'pointer',
                                transition: 'all 0.2s'
                            }}
                                onClick={() => {
                                    navigator.clipboard.writeText(name);
                                    alert('Copied to clipboard!');
                                }}
                            >
                                {name}
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            <FAQSection items={faqs} />
        </div>
    );
}
